In [2]:
import numpy as np

In [3]:
data1 = [3, 4, 5.6, 0, 1]
arr1 = np.array(data1)
arr1

array([3. , 4. , 5.6, 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
(arr2, arr2.shape, arr2.ndim)

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 (2, 4),
 2)

In [9]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int64'))

In [11]:
np.zeros(10)
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((2, 3, 2))

array([[[4.66554376e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
farr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
float_arr.dtype

int64


dtype('float64')

In [19]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [20]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [22]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [23]:
arr = np.arange(10)

In [24]:
arr[5]

5

In [25]:
arr[5:8]

array([5, 6, 7])

In [26]:
arr_slice = arr[5:8]
arr_slice[1] = 12
arr

array([ 0,  1,  2,  3,  4,  5, 12,  7,  8,  9])

In [27]:
arr_slice[:] = 10086
arr

array([    0,     1,     2,     3,     4, 10086, 10086, 10086,     8,
           9])

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0][2]

3

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# 这里取第二行的前两列
arr2d[1, 0:2]

array([4, 5])

In [33]:
arr2d[:2, 2]

array([3, 6])

In [39]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [43]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.random.randn(7, 4)
data

array([[-2.70093724e-01, -4.55880784e-01,  4.59848289e-01,
         4.16814347e-01],
       [-3.67248365e-01,  2.40225807e+00, -1.62152183e-01,
         9.13358645e-01],
       [-5.31418918e-01,  4.67834340e-01, -7.31372023e-01,
        -7.81748688e-01],
       [ 3.34410637e-01,  6.80033576e-01,  9.03663346e-01,
         1.36330701e-03],
       [-5.05072500e-01,  1.85860866e+00,  1.54294934e+00,
         1.00046064e+00],
       [-7.04288483e-01,  7.24289624e-01,  5.12863681e-01,
         2.52582206e+00],
       [ 2.71955275e-01, -1.88078130e+00, -1.07709726e-01,
         4.45397340e-01]])

In [45]:
data[names == "Bob"]

array([[-0.27009372, -0.45588078,  0.45984829,  0.41681435],
       [ 0.33441064,  0.68003358,  0.90366335,  0.00136331]])

In [46]:
mask = (names == "Bob") | (names == "Will")

In [48]:
data[mask]

array([[-2.70093724e-01, -4.55880784e-01,  4.59848289e-01,
         4.16814347e-01],
       [-5.31418918e-01,  4.67834340e-01, -7.31372023e-01,
        -7.81748688e-01],
       [ 3.34410637e-01,  6.80033576e-01,  9.03663346e-01,
         1.36330701e-03],
       [-5.05072500e-01,  1.85860866e+00,  1.54294934e+00,
         1.00046064e+00]])

In [49]:
data[data < 0] = 0

In [50]:
data

array([[0.00000000e+00, 0.00000000e+00, 4.59848289e-01, 4.16814347e-01],
       [0.00000000e+00, 2.40225807e+00, 0.00000000e+00, 9.13358645e-01],
       [0.00000000e+00, 4.67834340e-01, 0.00000000e+00, 0.00000000e+00],
       [3.34410637e-01, 6.80033576e-01, 9.03663346e-01, 1.36330701e-03],
       [0.00000000e+00, 1.85860866e+00, 1.54294934e+00, 1.00046064e+00],
       [0.00000000e+00, 7.24289624e-01, 5.12863681e-01, 2.52582206e+00],
       [2.71955275e-01, 0.00000000e+00, 0.00000000e+00, 4.45397340e-01]])

In [51]:
arr = np.arange(15).reshape((3, 5))

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [54]:
help(np.transpose)

Help on _ArrayFunctionDispatcher in module numpy:

transpose(a, axes=None)
    Returns an array with axes transposed.

    For a 1-D array, this returns an unchanged view of the original array, as a
    transposed vector is simply the same vector.
    To convert a 1-D array into a 2-D column vector, an additional dimension
    must be added, e.g., ``np.atleast2d(a).T`` achieves this, as does
    ``a[:, np.newaxis]``.
    For a 2-D array, this is the standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided, then
    ``transpose(a).shape == a.shape[::-1]``.

    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation
        of [0,1,...,N-1] where N is the number of axes of `a`. The `i`'th axis
        of the returned array will correspond to the axis numbe